<?php

namespace App\Http\Controllers;

use App\Models\Patient;
use Illuminate\Http\Request;

class PatientController extends Controller
{
    public function index()
    {
        $patients = Patient::orderBy('created_at', 'desc')
            ->orderBy('id', 'desc')
            ->paginate(10);

        return view('admin.patients.index', compact('patients'));
    }

    /**
     * Search patients by name, email, or phone
     */
    public function search(Request $request)
{
    $query = $request->get('q');
    
    $patients = Patient::with('user')
        ->whereHas('user', function($q) use ($query) {
            $q->where('name', 'like', "%{$query}%")
              ->orWhere('email', 'like', "%{$query}%");
        })
        ->orWhere('phone', 'like', "%{$query}%")
        ->orderBy('created_at', 'desc') // Add this line
        ->paginate(10);

    return view('admin.patients.index', compact('patients'));
}

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:patients,email',
            'phone' => 'required|string|max:20',
            'date_of_birth' => 'required|date',
            'gender' => 'required|in:Male,Female,Other',
            'blood_type' => 'required|string',
            'address' => 'required|string',
            'emergency_contact' => 'required|string',
        ]);

        // The patient_id and email will be auto-generated by the model boot method
        $patient = Patient::create([
            'user_id' => auth()->id(),
            'name' => $validated['name'],
            'email' => $validated['email'],
            'phone' => $validated['phone'],
            'date_of_birth' => $validated['date_of_birth'],
            'gender' => $validated['gender'],
            'blood_type' => $validated['blood_type'],
            'address' => $validated['address'],
            'emergency_contact' => $validated['emergency_contact'],
        ]);

        return redirect()->route('admin.patients.index')->with('success', 'Patient created successfully.');
    }

    public function show($id)
    {
        $patient = Patient::findOrFail($id);
        return view('admin.patients.show', compact('patient'));
    }
}